"""Static execution permission models and compilation boundary."""

from .audit import (
    NullPermissionAuditSink,
    PermissionAuditQuery,
    PermissionAuditSink,
    PermissionAuditStore,
    record_permission_audit,
)
from .authority import PermissionSnapshotAuthority, PermissionSnapshotProvider
from .command_gate import AuthorizedCommand, authorize_command
from .compiler import compile_permission_snapshot, diff_permission_snapshots, load_permission_templates
from .evaluator import combine_permission_decisions, evaluate_permission
from .path_gate import AuthorizedPath, authorize_path
from .network_gate import AuthorizedNetworkTarget, authorize_network_url
from .process_gate import ProcessFacts, authorize_process
from .models import (
    AgentWorkspaceBoundary,
    AgentPermissionSpec,
    CommandConstraints,
    CommandResource,
    CommandSelector,
    CodeEgressProxySpec,
    ExternalPathResource,
    ExternalPathSelector,
    MatchAllSelector,
    NetworkConstraints,
    NetworkResource,
    NetworkSelector,
    NoConstraints,
    NodePermissionSpec,
    PathConstraints,
    PermissionChange,
    PermissionDecision,
    PermissionRequest,
    PermissionRule,
    PermissionSource,
    PermissionSubject,
    PermissionTemplate,
    ProcessConstraints,
    ProcessResource,
    ProcessSelector,
    ResolvedPermissionDefault,
    ResolvedPermissionRule,
    ResolvedPermissionRollout,
    ResolvedPermissionSnapshot,
    TemplatePermissionRule,
    ToolResource,
    ToolSelector,
    WorkspacePathResource,
    WorkspacePathSelector,
    allowed_actions_for,
)
from .tooling import PermissionToolDescriptor, ToolSource, describe_adk_tool

__all__ = [
    "AgentWorkspaceBoundary",
    "AgentPermissionSpec",
    "AuthorizedCommand",
    "AuthorizedPath",
    "AuthorizedNetworkTarget",
    "CommandConstraints",
    "CommandResource",
    "CommandSelector",
    "CodeEgressProxySpec",
    "ExternalPathResource",
    "ExternalPathSelector",
    "MatchAllSelector",
    "NetworkConstraints",
    "NetworkResource",
    "NetworkSelector",
    "NoConstraints",
    "NullPermissionAuditSink",
    "NodePermissionSpec",
    "PathConstraints",
    "PermissionChange",
    "PermissionAuditQuery",
    "PermissionAuditSink",
    "PermissionAuditStore",
    "PermissionSnapshotAuthority",
    "PermissionSnapshotProvider",
    "record_permission_audit",
    "PermissionDecision",
    "PermissionRequest",
    "PermissionRule",
    "PermissionSource",
    "PermissionSubject",
    "PermissionTemplate",
    "PermissionToolDescriptor",
    "ProcessConstraints",
    "ProcessFacts",
    "ProcessResource",
    "ProcessSelector",
    "ResolvedPermissionDefault",
    "ResolvedPermissionRule",
    "ResolvedPermissionRollout",
    "ResolvedPermissionSnapshot",
    "TemplatePermissionRule",
    "ToolSource",
    "ToolResource",
    "ToolSelector",
    "WorkspacePathResource",
    "WorkspacePathSelector",
    "allowed_actions_for",
    "authorize_path",
    "authorize_network_url",
    "authorize_process",
    "authorize_command",
    "compile_permission_snapshot",
    "combine_permission_decisions",
    "describe_adk_tool",
    "diff_permission_snapshots",
    "evaluate_permission",
    "load_permission_templates",
]
