"""Stable capabilities advertised by the in-process Control Plane kernel."""

CONTROL_PLANE_CAPABILITIES: tuple[str, ...] = (
    "actions.catalog",
    "actions.invoke",
    "config.agent.read",
    "config.agent.write",
    "config.node.read",
    "config.node.write",
    "extension.auth",
    "extension.read",
    "extension.write",
    "model.profiles.read",
    "model.profiles.write",
    "model.select",
    "operations.read",
    "operations.write",
    "audit.read",
    "run.control",
    "session.read",
    "session.write",
    "secret.read",
    "secret.write",
    "setup.read",
    "setup.write",
    "task.read",
    "system.status",
)
