import type { ArtifactSummary, ChatMessage } from "../types";
import { projectActivityGroups } from "./activity-presentation";

export interface ActivityItem {
  id: string;
  kind: "step" | "tool" | "error";
  title: string;
  detail: string;
  status: "running" | "completed" | "failed";
  messageId: string;
  count: number;
}

export interface ArtifactItem {
  id: string;
  kind: "file" | "image";
  title: string;
  description: string;
  mimeType?: string;
  sizeBytes?: number;
  url?: string;
  messageId: string;
  resource?: ArtifactSummary;
}

/** Project transcript parts into a stable, inspectable activity timeline. */
export function projectActivityItems(messages: ChatMessage[]): ActivityItem[] {
  const activity = projectActivityGroups(messages).map((group) => ({
    id: `activity:${group.key}`,
    kind: "tool" as const,
    title: group.label,
    detail: group.count > 1 ? group.countLabel : group.entries[0]?.detail || group.countLabel,
    status: group.status,
    messageId: group.messageId,
    count: group.count,
  }));
  const errors = messages.flatMap((message) => message.parts.flatMap((part, index) => part.type === "error" ? [{
    id: `error:${message.id}:${index}`,
    kind: "error" as const,
    title: part.errorCode || "Run error",
    detail: part.text,
    status: "failed" as const,
    messageId: message.id,
    count: 1,
  }] : []));
  return [...activity, ...errors];
}

/** Project existing file and image message parts without inventing an artifact backend. */
export function projectArtifactItems(messages: ChatMessage[]): ArtifactItem[] {
  const items = new Map<string, ArtifactItem>();
  messages.forEach((message) => {
    message.parts.forEach((part, index) => {
      if (part.type === "file") {
        const id = `file:${part.fileName}`;
        items.set(id, {
          id,
          kind: "file",
          title: part.fileName,
          description: part.text,
          mimeType: part.mimeType,
          sizeBytes: part.sizeBytes,
          messageId: message.id,
        });
      } else if (part.type === "image") {
        const id = `image:${part.url || `${message.id}:${index}`}`;
        items.set(id, {
          id,
          kind: "image",
          title: part.text || "Image",
          description: "Image artifact from the current session.",
          mimeType: part.mimeType,
          url: part.url,
          messageId: message.id,
        });
      }
    });
  });
  return [...items.values()];
}

/** Merge durable Node artifact resources with transcript-derived message parts. */
export function mergeArtifactResources(messages: ChatMessage[], resources: ArtifactSummary[]): ArtifactItem[] {
  const projected = projectArtifactItems(messages);
  const durable = resources.map((resource) => ({
    id: `resource:${resource.id}`,
    kind: resource.mimeType.startsWith("image/") ? "image" as const : "file" as const,
    title: resource.fileName,
    description: resource.source === "user_upload" ? "Uploaded with this Session." : "Generated by the Agent.",
    mimeType: resource.mimeType,
    sizeBytes: resource.sizeBytes,
    messageId: "",
    resource,
  }));
  const resourceNames = new Set(durable.map((item) => item.title));
  return [...durable, ...projected.filter((item) => !resourceNames.has(item.title))];
}
