import type { ArtifactSummary, ChatMessage, MessagePart } from "../types";

export interface ActivityItem {
  id: string;
  kind: "step" | "tool" | "error";
  title: string;
  detail: string;
  status: "running" | "completed" | "failed";
  messageId: string;
}

export interface ArtifactItem {
  id: string;
  kind: "file" | "image";
  title: string;
  description: string;
  mimeType?: string;
  sizeBytes?: number;
  url?: string;
  messageId: string;
  resource?: ArtifactSummary;
}

function activityFromPart(message: ChatMessage, part: MessagePart, index: number): ActivityItem | null {
  if (part.type === "step_ref") {
    return {
      id: `step:${part.stepId}`,
      kind: "step",
      title: part.title,
      detail: part.detail,
      status: part.status,
      messageId: message.id,
    };
  }
  if (part.type === "tool_result") {
    return {
      id: `tool:${message.id}:${index}`,
      kind: "tool",
      title: part.toolName,
      detail: part.detail ? `${part.summary}\n${part.detail}` : part.summary,
      status: message.status === "failed" ? "failed" : "completed",
      messageId: message.id,
    };
  }
  if (part.type === "error") {
    return {
      id: `error:${message.id}:${index}`,
      kind: "error",
      title: part.errorCode || "Run error",
      detail: part.text,
      status: "failed",
      messageId: message.id,
    };
  }
  return null;
}

/** Project transcript parts into a stable, inspectable activity timeline. */
export function projectActivityItems(messages: ChatMessage[]): ActivityItem[] {
  const orderedIds: string[] = [];
  const items = new Map<string, ActivityItem>();
  messages.forEach((message) => {
    message.parts.forEach((part, index) => {
      const item = activityFromPart(message, part, index);
      if (!item) {
        return;
      }
      if (!items.has(item.id)) {
        orderedIds.push(item.id);
      }
      items.set(item.id, item);
    });
  });
  return orderedIds.map((id) => items.get(id)!).filter(Boolean);
}

/** Project existing file and image message parts without inventing an artifact backend. */
export function projectArtifactItems(messages: ChatMessage[]): ArtifactItem[] {
  const items = new Map<string, ArtifactItem>();
  messages.forEach((message) => {
    message.parts.forEach((part, index) => {
      if (part.type === "file") {
        const id = `file:${part.fileName}`;
        items.set(id, {
          id,
          kind: "file",
          title: part.fileName,
          description: part.text,
          mimeType: part.mimeType,
          sizeBytes: part.sizeBytes,
          messageId: message.id,
        });
      } else if (part.type === "image") {
        const id = `image:${part.url || `${message.id}:${index}`}`;
        items.set(id, {
          id,
          kind: "image",
          title: part.text || "Image",
          description: "Image artifact from the current session.",
          mimeType: part.mimeType,
          url: part.url,
          messageId: message.id,
        });
      }
    });
  });
  return [...items.values()];
}

/** Merge durable Node artifact resources with transcript-derived message parts. */
export function mergeArtifactResources(messages: ChatMessage[], resources: ArtifactSummary[]): ArtifactItem[] {
  const projected = projectArtifactItems(messages);
  const durable = resources.map((resource) => ({
    id: `resource:${resource.id}`,
    kind: resource.mimeType.startsWith("image/") ? "image" as const : "file" as const,
    title: resource.fileName,
    description: resource.source === "user_upload" ? "Uploaded with this Session." : "Generated by the Agent.",
    mimeType: resource.mimeType,
    sizeBytes: resource.sizeBytes,
    messageId: "",
    resource,
  }));
  const resourceNames = new Set(durable.map((item) => item.title));
  return [...durable, ...projected.filter((item) => !resourceNames.has(item.title))];
}
