"""OpenPPX Extension Platform domain boundary."""

from .errors import ExtensionError
from .app_adapters import (
    NativeAppAdapter,
    NativeAppAdapterProbe,
    NativeAppAdapterReadiness,
    NativeAppAdapterRegistry,
    NativeAppContext,
)
from .native_app_adapters import default_native_app_adapter_registry
from .apps import (
    AppManager,
    AppReadiness,
    AppSnapshot,
    AppSnapshotEntry,
    VersionedAppConnection,
    VersionedAppDefinition,
)
from .mcp import (
    McpManager,
    McpReadiness,
    McpSnapshot,
    McpSnapshotEntry,
    VersionedMcp,
    merge_mcp_snapshots,
)
from .mcp_models import McpServer
from .plugin_models import PluginManifest, PluginRecord
from .plugin_marketplace import (
    PluginMarketplaceEntry,
    PluginMarketplaceManager,
    PluginMarketplaceSourceRecord,
    PluginMarketplaceSourceSpec,
    VersionedPluginMarketplaceSource,
)
from .plugin_hooks import (
    PluginHookExecutor,
    PluginHookRejected,
    PluginHookSnapshot,
    PluginHookStatus,
)
from .plugins import (
    PluginManager,
    PluginPreview,
    PluginReadiness,
    PluginSnapshot,
    PluginSnapshotEntry,
    StagedPlugin,
    VersionedPlugin,
    parse_plugin_manifest,
)
from .registry import ExtensionDetail, ExtensionKind, ExtensionRegistry, ExtensionSummary
from .starter_catalog import (
    ExtensionStarter,
    ExtensionStarterCatalog,
    default_extension_starter_catalog,
)
from .models import (
    ExtensionPresentation,
    ExtensionSourceIdentity,
    ExtensionSourceRef,
    ExtensionSourceType,
    SkillDependencies,
    SkillManifest,
    SkillRecord,
    SkillRecordSpec,
)
from .skills import (
    SkillManager,
    SkillPreview,
    SkillReadiness,
    SkillSnapshot,
    SkillSnapshotEntry,
    StagedSkill,
    VersionedSkill,
    merge_skill_snapshots,
    parse_skill_manifest,
)

__all__ = [
    "ExtensionError",
    "ExtensionDetail",
    "ExtensionKind",
    "ExtensionRegistry",
    "ExtensionSummary",
    "ExtensionStarter",
    "ExtensionStarterCatalog",
    "default_extension_starter_catalog",
    "AppManager",
    "AppReadiness",
    "AppSnapshot",
    "AppSnapshotEntry",
    "NativeAppAdapter",
    "NativeAppAdapterProbe",
    "NativeAppAdapterReadiness",
    "NativeAppAdapterRegistry",
    "NativeAppContext",
    "default_native_app_adapter_registry",
    "McpManager",
    "McpReadiness",
    "McpServer",
    "McpSnapshot",
    "McpSnapshotEntry",
    "PluginManager",
    "PluginMarketplaceEntry",
    "PluginMarketplaceManager",
    "PluginMarketplaceSourceRecord",
    "PluginMarketplaceSourceSpec",
    "PluginHookExecutor",
    "PluginHookRejected",
    "PluginHookSnapshot",
    "PluginHookStatus",
    "PluginManifest",
    "PluginPreview",
    "PluginReadiness",
    "PluginRecord",
    "PluginSnapshot",
    "PluginSnapshotEntry",
    "ExtensionPresentation",
    "ExtensionSourceIdentity",
    "ExtensionSourceRef",
    "ExtensionSourceType",
    "SkillDependencies",
    "SkillManager",
    "SkillManifest",
    "SkillPreview",
    "SkillReadiness",
    "SkillRecord",
    "SkillRecordSpec",
    "SkillSnapshot",
    "SkillSnapshotEntry",
    "StagedSkill",
    "StagedPlugin",
    "VersionedSkill",
    "VersionedPlugin",
    "VersionedPluginMarketplaceSource",
    "VersionedMcp",
    "VersionedAppConnection",
    "VersionedAppDefinition",
    "merge_mcp_snapshots",
    "merge_skill_snapshots",
    "parse_plugin_manifest",
    "parse_skill_manifest",
]
